# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas


class Ui_MainWindow(object):

    def plot_data(self, sData):
        print('Hello')

    def button_action(self, sData):
        self._currentStock = sData.get_ind_str()
        self.plot_data(sData) 

    def create_button(self, sData, buttonInd):
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(870, 50*buttonInd + 50, 151, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(lambda: self.button_action(sData))

        _translate = QtCore.QCoreApplication.translate
        self.pushButton.setText(_translate("MainWindow", sData.get_name()))

    def create_button_by_stock_database(self, stockDataBase):
        sDataDict = stockDataBase.get_dataDict()
        buttonInd = 0
        for stockInd in sDataDict:
            sData = sDataDict[stockInd]
            self.create_button(sData, buttonInd)
            buttonInd += 1

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("StockView")
        MainWindow.resize(1136, 797)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(30, 60, 781, 611))
        self.graphicsView.setObjectName("graphicsView")


        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 161, 31))
        self.label.setObjectName("label")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1136, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)


    fig1 = plt.figure()

    ax1 = fig1.add_subplot(1,2,1)
    ax1.plot(range(1,6), [11, 10, None, 12, 13 ])

    scene = QtWidgets.QGraphicsScene()
    # QtWidgets.QGraphicsScene().add
    scene.addWidget(FigureCanvas(fig1))
    ui.graphicsView.setScene(scene)
    ui.graphicsView.show()
    MainWindow.show()
    sys.exit(app.exec_())
